### ISSUE TITLE
Undefined mixin vendor

### ISSUE THREAD

**Issue by tillnagel** [ozgrozer/dasper#3]
After updating SCSS I try to generate the CSS but get an error in dev/reset.scss (Line 24: Undefined mixin 'vendor1'.)

**Comment by ozgrozer** [comment]
In the reset.scss the mixins.scss file is importing (`@import "mixins";`) and in the mixins.scss there is a vendor1 mixing (`@mixin vendor1($property, $expression...)`). So there is no problem in codebase. How do you compile the scss files?

**Comment by tillnagel** [comment]
Thanks. Was on my side, I had messed up the mixins.scss by trying to generate the css.

`sass assets/css/dev/style.scss:assets/css/prod/style.min.css --style compressed` works fine.
