### ISSUE TITLE
Xml highlighting not work

### ISSUE THREAD

**Issue by VasilievPavel96** [ozgrozer/dasper#4]
![image](https://user-images.githubusercontent.com/22943591/32266201-7bceca78-bef7-11e7-8f26-614e2495bf15.png)
I used this to highlight it, but i get white font color.
``{% highlight xml %}
<uses-permission android:name="android.permission.SEND_SMS"/>
{% endhighlight %}``

**Comment by ozgrozer** [comment]
You can use like that.

![1](https://user-images.githubusercontent.com/651938/32282861-cd05ae5c-bf33-11e7-89ed-205863e985f7.jpg)

![2](https://user-images.githubusercontent.com/651938/32282862-cd230dd0-bf33-11e7-9ec1-4aa40a60fa76.jpg)
